POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "theacexxyyy",
    "email":"theacexxyyy@gmail.com",
    "password": "theace"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"theace@gmail.com",
    "password": "theace"
}

###

POST http://localhost:5000/ticket
Content-Type: application/json

{
    "username": "Ace Technlogies",
    "ticket_type":"BRONZE"
}

###

GET http://localhost:5000/init
Content-Type: application/json


###

POST http://localhost:5000/contact
Content-Type: application/json

{
    "email": "theaxe@gmail.com",
    "message":"Let's just cook",
    "fullname": "Andrea Martinez"
}

###

POST http://localhost:5000/keepmeupdated
Content-Type: application/json

{
    "email":"iloenyenwavictor@gmail.com"
}

###

POST https://techverse-v2.onrender.com/register
Content-Type: application/json

{
    "username": "theacex",
    "email":"theacex@gmail.com",
    "password": "theacex"
}

###

POST https://techverse-v2.onrender.com/login
Content-Type: application/json

{
    "email":"theace@gmail.com",
    "password": "theace"
}


###

POST https://techverse-v2.onrender.com/keepmeupdated
Content-Type: application/json

{
    "email":"iloenyenwavictor@gmail.com"
}

###

POST https://techverse-v2.onrender.com/contact
Content-Type: application/json

{
    "email": "theaxe@gmail.com",
    "message":"Let's just cook",
    "fullname": "Andrea Martinez"
}
